language: python

git:
    submodules: false

# before_install:
#     - git submodule update --init --recursive

# need packages for converting md to pdf/html and latex
# for equations
addons:
  apt:
    packages:
    - pandoc
    - texlive-latex-base
    - texlive-latex-recommended

install:
    - ls -al website
    - pip install -U pip setuptools wheel
    # - pip install -U typogrify Markdown
    # - pip install -U pelican

script:
    - ls -al website
    - ./website/build_html.sh
    - cd website && ./build_html.sh

# WARNING: deploy will wipe out everything, so setup your deployment
# to gh-pages branch in the github settings drop down ... NOT master!
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
    local_dir: website/www  # grab the contents of this for webpage
    project_name:  marsuniversity.github.io
    repo: MarsUniversity/ece387
    target_branch: gh-pages
    on:
        branch: master
